source=~/.config/hypr/startup.conf

monitor = eDP-1,1920x1080@60,0x0,1
monitor = eDP-1,addreserved,5,10,10,10
workspace = eDP-1,2

general {
    gaps_in = 5
    gaps_out = 4
    border_size = 1
    col.active_border = 0x1e1e1e1e00
    col.inactive_border = 0xFF42424200
    col.group_border = rgba(2b2e2e90)
    col.group_border_active = rgb(2b2e2e)
    no_focus_fallback = true
}

decoration {
    rounding = 9
    multisample_edges = true

    blur = yes
    blur_size = 5
    blur_passes = 4
    blur_new_optimizations = true
#   blur_xray = true
#   blur_ignore_opacity = true

    drop_shadow = true
    shadow_range = 15
    shadow_render_power = 3
    col.shadow = rgba(00000054)
    shadow_ignore_window = true

    dim_special = 0.6

#   screen_shader = ~/.config/hypr/scripts/screenShader.frag
}

animations {
    enabled = yes
    animation = windows,1,1,default,popin
    animation = workspaces,1,1,default
    animation = fade,1,1,default
    animation = specialWorkspace,1,1,default,slidevert
}

input {
    follow_mouse = 1
    #repeat_rate = 40
    #repeat_delay = 300
    numlock_by_default = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = 1
    }     
}     

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_forever = true
#   workspace_swipe_numbered = true
}     

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
#   layers_hog_keyboard_focus = false
    animate_manual_resizes = true
    no_direct_scanout = true
    enable_swallow = true 
#    vrr = 1
    enable_swallow = true
    swallow_regex = kitty
    focus_on_activate = true
}

binds {
    workspace_back_and_forth = false
    allow_workspace_cycles = false
  }

rules {
   #windowrule = fullscreen,(mpv)$
    windowrule = size 300 300,title:^(wifish)$
    windowrule = move 1600 60,title:^(wifish)$
    windowrule = float,title:^(wifish)$
    windowrule = float,title:^(Eyedropper)$
    windowrule = float,title:^(Volume Control)$
    windowrule = noanim,title:^(zsh)$
    windowrule = noanim,class:^(kitty)$
    windowrule = float,class:^(xdg-desktop-portal-gtk)$


    windowrulev2 = float,class:^()$,title:^(Picture in picture)$
    windowrulev2 = float,class:^(brave)$,title:^(Save File)$
    windowrulev2 = float,class:^(brave)$,title:^(Open File)$
    windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
    windowrulev2 = float,class:^(firefox)$,title:^(Library)$
    windowrulev2 = float,class:^(firefox)$,title:^(Choose Application)$

    layerrule = blur,powermenu_eww
    layerrule = blur,eww_background
}

dwindle {
    special_scale_factor = 0.94
    pseudotile = true
    preserve_split = true
  }

source=~/.config/hypr/binds.conf
