#!/bin/bash
STATE=$(cat $HOME/.cache/eww/player/ly-status)
if [[ $STATE == "On" ]]; then
    eww close lyrics
    pkill glava 
    eww close visualizer
    echo "Off" > $HOME/.cache/eww/player/ly-status
else
    eww open lyrics
    eww close visualizer &
    pkill visualizer
    echo "On" > $HOME/.cache/eww/Player/ly-status
fi
exit
