#!/bin/sh

STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"

if [ "$STATUS" = "no" ]; then
    rfkill block 0
    notify-send --urgency=normal "Airplane Mode" "Airplane mode has been turned on!"
else
    rfkill unblock 0
    notify-send --urgency=normal "Airplane Mode" "Airplane mode has been turned off!"
fi
