#!/usr/bin/env bash
STATUS=$(awk '/%/ {gsub(/[\[\]]/,""); print $6}' <(amixer sget Master) | awk 'FNR == 1')
toggle() {
    if [ $STATUS == "on" ]; then
        amixer set Master toggle
        notify-send --icon=volume-level-muted --urgency=normal "Volume " "Volume has been muted!"
        # eww -c ~/.config/eww/System-Menu/ update main-volume-box=main-volume-box-off
    else
        amixer set Master toggle
        notify-send --icon=volume-level-high --urgency=normal "Volume" "Volume has been unmuted!"
        # eww -c ~/.config/eww/System-Menu/ update main-volume-box=main-volume-box-on
    fi
}

icon() {
    if [ $STATUS == "on" ]; then
        echo "󰕾"
    else
        echo "󰖁"
    fi
}

status() {
    if [ $STATUS == "on" ]; then
        echo "On"
    else
        echo "Off"
    fi
}

col() {
    if [ $STATUS == "on" ]; then
        echo "main-volume-box-off"
    else
        echo "main-volume-box-on"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
elif [[ $1 == "col" ]]; then
    col
fi
